name: lint
on:
  push:
    branches: [main]
  pull_request:
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check the shell scripts
        run: shellcheck -s sh upload/upload.sh setup-linux.sh remove-linux.sh setup-mac.command remove-mac.command
